---
title: "Parallel Iterations of Strava Data"
author: "Makayla Whitney, Joe Swinehart, Janette Avelar, David Fainstein"
date: "5/19/2021"
slug: functional-programming-with-strava-data
categories: R
tags:
- R
- Strava
---


```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#note: include = FALSE and echo = FALSE for now, but it will still print messages and can be coerced to show full chunks of code if we desire

library(tidyverse)
library(purrr)
library(repurrrsive)
library(here)
library(janitor)
library(lubridate)

```

Strava is an excellent way to keep track of physical activity on an individual basis. 

We will begin by reading in a batch of data from one individual.

```{r conversion_function}
yardstometers <- function(yards, swimming) {
  ifelse(swimming, yards * 1.09361, yards)
}

```

```{r SufficientActivities}
# Using proportions could be useful to select only the most common activities (e.g., >1%)
proportions_activity <- function(activities, threshold = 0.02) {
  temp <- map_dbl(split(activities, activities), length) / length(activities)
  d <- data.frame(act_type = names(temp),
             gt_threshold = temp > threshold)
  d[d$gt_threshold, "act_type", drop = FALSE]
}
```


```{r firststep}
#reading in data for sandbox
strav_data <- read_csv(here("content/post/2021-04-16-functional-programming-with-strava-data/data", "strav_csv.csv"))

tidyfunc <- strav_data %>% 
  select(where(~length(unique(.)) > 1)) %>%
    # selecting unique values
  mutate(type = as.factor(type)) %>% 
  dplyr::rename(act_type = type) %>% 
  clean_names() %>% 
  mutate(is_swimming = act_type == "swimming",
         distance = yardstometers(distance, is_swimming)) %>% 
    # rounding values to remove clutter for visualization
  separate(start_date_local, c("date","time"), sep = " ") %>% 
  select(-start_date) %>% 
    #separating out date & time; excluding multiple dates and times
  filter(elapsed_time > 0,
         max_speed > average_speed)
    # removes activities with no duration (which rules out manually entered activities where no time is supplied) and also incorrect calculations where Strava defines the an average speed that is higher than the max speed (this most often occurs in swimming)

tidy_data <- semi_join(tidyfunc, proportions_activity(tidyfunc$act_type))



```

Then we will create a function that allows us to turn dates into days of the week and times into periods during the day. This will help us to categorize activities by days of the week and time periods within the day.

```{r secondstep}

daysoftheweek <- function(x) format(as.Date(x), "%A")

library(glue)

#creating data
weeklydata <- tidy_data %>%
  mutate(weekday = daysoftheweek(date)) %>% 
  group_by(act_type) %>% 
  nest() %>% 
  mutate(plots = map2(data, act_type, ~{
    ggplot(.x, aes(weekday)) +
      geom_histogram(stat = "count") +
      labs(title = glue("Number of {.y} by Days of the Week"),
          x = "",
          y = glue("Number of {.y}"))
  }))


#one plot displaying a count of hikes by days of the week
oneplot <- weeklydata %>%
  filter(act_type == "Hike") %>%
  ggplot(aes(weekday)) +
  geom_histogram(stat = "count") +
  guides(fill = "none") +
      labs(title = "Number of Hikes by Days of the Week",
           x = "",
           y = "Number of Hikes")


#multiple plots based on activity 
byact <- weeklydata <- tidy_data %>%
  mutate(weekday = daysoftheweek(date)) %>%
  group_by(act_type) %>%
  nest() %>%
  mutate(plots = map(data, ~{
    ggplot(.x, aes(weekday)) +
      geom_histogram(stat = "count")
  }))

#display plot
weeklydata$plots[[2]]



```


```{r fourthstep}

#saving plots
#create a directory
fs::dir_create(here::here("final_plots", "eugeneroads"))
paths <- here::here("final_plots", "eugeneroads", glue("{eugeneroads}.png"))

#trying to find a way to fit this in
walk2(paths, final_plots$eugeneroads, ggsave,
      width = 9.5, 
      height = 6.5,
      dpi = 500)

````

