---
title: "Real-World Applications for Strava Data"
author: "Makayla Whitney, Joe Swinehart, Janette Avelar, David Fainstein"
date: "5/19/2021"
slug: functional-programming-with-strava-data
categories: R
tags:
- R
- Strava
---


```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#note: include = FALSE and echo = FALSE for now, but it will still print messages and can be coerced to show full chunks of code if we desire

library(tidyverse)
library(purrr)
library(repurrrsive)
library(here)
library(janitor)
library(lubridate)

```

This will produce an overlay of the Strava data (specifically bike rides) on top of Eugene, Oregon bike paths. City planners use Strava data to understand high-use areas within the city to help avoid accidents involving bikers and runners. 


```{r firststep}
#reading in data for sandbox
strav_data <- read_csv(here("content/post/2021-04-16-functional-programming-with-strava-data/data", "strav_csv.csv"))

#initial function for tidying Stravadata
tidymap <- strav_data %>% 
  select(where(~length(unique(.)) > 1)) %>%
    # selecting unique values
  clean_names() %>% 
  mutate_if(is.numeric, ~round(., 2)) %>% 
    # rounding values to remove clutter for visualization
  mutate(type = as.factor(type)) %>% 
  separate(start_date_local, c("date","time"), sep = " ") %>% 
  select(-start_date) %>% 
    #separating out date & time; excluding multiple dates and times
  filter(elapsed_time > 0,
         max_speed > average_speed)

#further filter
filteredmap <- tidymap %>%
  select(distance,
         timezone,
         type)

```


```{r secondstep}
#load in Eugene, OR road map (borrowed from W21 lecture on 4/28)
library(tigris)
library(sf)
library(glue)
options(tigris_class = "sf")
roads_laneco <- roads("OR", "Lane")

eugeneroads <- ggplot(roads_laneco) +
  geom_sf(color = "gray60")


```


```{r thirdstep}

````


```{r fourthstep}

#saving plots
#create a directory
fs::dir_create(here::here("final_plots", "eugeneroads"))
paths <- here::here("final_plots", "eugeneroads", glue("{eugeneroads}.png"))

#trying to find a way to fit this in
walk2(paths, final_plots$eugeneroads, ggsave,
      width = 9.5, 
      height = 6.5,
      dpi = 500)

````

